commerce_recurring.commerce_recurring_type.*:
  type: config_entity
  label: 'Recurring type'
  mapping:
    label:
      type: label
      label: 'Label'
    id:
      type: string
      label: 'Machine-readable name'
